Merge branch 'merge_WCSim_v1.11.0' of https://github.com/kmtsui/WCSim…
WCSim/WCSim pull request #353
Opened 2023-06-12 04:29 UTC by kmtsui

Merge WCTE/WCSim into the latest WCSim/WCSim

Still need to modify the NoReplica construction method to include hybrid config and OD.

2023-06-15 09:59 UTC, tdealtry requested changes
Thanks for this @kmtsui 

I've had a quick look at the config files and have a few suggestions to make what options mean clearer

My standard validation for HK FD/IWCD/SK is running - will report the results later today

2023-06-15 09:59 UTC, tdealtry commented on WCSim.mac
> +#/WCSim/WCgeom nuPRISMShort_mPMT
Can you elaborate a little on this? Something like

```suggestion
#Use IWCD or WCTE geometry (uncomment/delete the above)
# Use the (old or new?) IWCD geometry
#/WCSim/WCgeom nuPRISM_mPMT
# Use the WCTE geometry
#/WCSim/WCgeom nuPRISMBeamTest_mPMT
# Use the (old or new?) IWCD geometry
#/WCSim/WCgeom nuPRISMShort_mPMT
```

2023-06-15 09:59 UTC, tdealtry commented on WCSim.mac
> +# True --> default replica method to place PMTs. False --> new placement method
Can you elaborate on new vs old?

2023-06-15 09:59 UTC, tdealtry commented on mPMT-configfiles/mPMTconfig_Position_WCTE.txt
> +PMT position table for custom PMT placement. The direction is just for referenec by not used.
You've got a typo here, and a grammar mistake. I think this is what you mean
```suggestion
PMT position table for custom PMT placement. The direction is just for reference and is not used.
```

2023-06-15 09:59 UTC, tdealtry commented on macros/nuPRISMBeamTest.mac
> +# nuPRISMBeamTest WCTE macro with no visualization
Naive question, but why not call this WCTE.mac?

2023-06-15 09:59 UTC, tdealtry commented on macros/tuning_parameters.mac
> +# Set to "0" to use default model, "1" or "2" to use new models
What are the new models? Please elaborate. References are also useful

2023-06-15 09:59 UTC, tdealtry commented on macros/tuning_parameters.mac
> +# 0 = (Seems to be) SK. 1 = KCsCb, 2 = RbCsCb from Model2's paper
I'm guessing that these are found in the same paper as **photocathode** model 2?
```suggestion
# 0 = (Seems to be) SK. 1 = KCsCb, 2 = RbCsCb [1 and 2 from from pmtsurftype Model2's paper]
```

2023-06-15 09:59 UTC, tdealtry commented on src/WCSimVisManager.cc
> +
Already included
```suggestion
```

2023-06-15 09:59 UTC, tdealtry commented on bunny.stl
Can you move this into `$WCSIMDIR/macros` or `$WCSIMDIR/data`, just to keep the root dir cleaner?

This also leads to a change in `WCSimConstructCylinder.cc`, updating the (dummy hardcoded) path to this file, in the places where it's commented out.

2023-06-15 15:59 UTC, tdealtry commented
The current status of my validation between debb4f6 and v1.11.0 is
- nPMTs agree in all geometries (SK/IWCD/HK FD hybrid/HK FD complete). PMT positions from `geofile.txt` also agree
- Number of killed tracks (`GeomNav1002`) consistent (i.e. 0 or 1 per 1000 events in HK/IWCD geometries, up to 12000 per 1000 events in SK)
- `nuPRISMShort_mPMT` geometry has perfect agreement
- SK geometry has differences order 1% in nhits & ndigits
- HK hybrid geometry has differences order 1% in nhits & ndigits (for both PMT types)
- HK complete geometry has 
  - differences order 1% in nhits & ndigits (for all PMT types) for events starting in the ID
  - differences of ~7% for 20"/mPMT nhits & ndigits for events starting in the barrel OD, punching into the ID. OD hits at ~1% level.
  - Weirdly, perfect agreement for all PMT types for events starting in the barrel OD, directed upwards.

Before merging, I would like to understand why there is perfect agreement in IWCD, but not in SK/HK (other than the one for HK OD)

2023-06-16 02:46 UTC, kmtsui commented
I prioritized the change of cap/blacksheet geometry to WCTE, let me check this part again

2023-06-16 09:46 UTC, kmtsui commented
I will need compatibility with ROOT5. Do you mind I push back the old GNUmakefile (with some additional flags) to make it compile?

2023-06-16 11:29 UTC, tdealtry commented
Yeah go ahead & push the Makefile back

The important thing is to keep the README accurate with the recommended (and fully supported) setup i.e. cmake, root6 & Geant4.10.3.3

2023-06-16 13:36 UTC, kmtsui commented
Ok it seems that the [G4LogicalSkinSurface of border ring blacksheet](https://github.com/WCSim/WCSim/pull/353/commits/aedb7cdb20dc009cc78479d796c09ffe2c52792a) is important to reduce "the photon is killed" warning. This could be the reason for the SK/HK differences

2023-06-27 02:09 UTC, tdealtry commented
I've rerun the standard validation on 9fd4a75 and still see the same
- PMT positions identical in all geometries
- Number of killed tracks (GeomNav1002) consistent
- nuPRISMShort_mPMT (all physics) and HK FD complete (only starting in OD barrel, aimed upwards) have perfect agreement
- Other geometries/physics have differences
  - 3-8% difference for events starting in HK FD complete OD barrel, pointing into ID
  - ~1% difference for everything else

I'd still like to understand why there's perfect agreement for some things and not others. Given what the differences are, I presume there is a change to the SK/HK FD (ID part) geometries, but not the IWCD/HK FD (OD part) geometries

2023-06-27 02:17 UTC, kmtsui commented
I suspect that is due ot the [G4LogicalSkinSurface of border ring blacksheet](https://github.com/WCSim/WCSim/pull/353/commits/aedb7cdb20dc009cc78479d796c09ffe2c52792a)

Can you try running validation on [224cc4c](https://github.com/WCSim/WCSim/pull/353/commits/224cc4c0bac670f2cc11243373c3a495b1e4176c) instead? This one should give the same G4LogicalSkinSurface setting as the standard WCSim. Or I can push another commit that reverts the setup.

2023-07-26 14:06 UTC, tdealtry commented
The CI is working now, mostly fine. But unfortunately I can't see how to get your branch using the new CI file myself. Can you do something like a `git pull && git push` (I think only changes are to `.github/workflows`, so there shouldn't be any conflicts)

2023-07-27 03:00 UTC, kmtsui commented
Just did a pull and push. The `TEST_SK_5MeVem_centre_xdir` plots are generated but not the others. Something wrong?

2023-07-28 17:03 UTC, tdealtry commented
Think you need to pull again actually. In the build job I was originally doing a quick 5MeV SK test with ~10 events... which failed...

Why did it fail? Simply because you have a different number of stuck track warnings. Your number is much improved (i.e. it is 0)

Anyway I've changed the CI logic such that the build job doesn't run any physics checks, it just sets up the webpage. And I moved the 5MeV SK test into the physics matrix, such that all jobs are guaranteed to run and report their status (assuming the build job completes)

2023-08-10 08:45 UTC, kmtsui commented
Correspond to issues https://github.com/WCSim/WCSim/issues/348, https://github.com/WCSim/WCSim/issues/349, https://github.com/WCSim/WCSim/issues/350, https://github.com/WCSim/WCSim/issues/351

2023-08-10 08:46 UTC, kmtsui commented
Rotate half a barrel for WCTE from https://github.com/WCTE/WCSim/pull/12

2023-08-10 13:44 UTC, tdealtry requested changes
This is a lot of good work, and it's nice to see that this isn't changing the physics output of things for HK/IWCD. Thanks @kmtsui and the rest of WCTE

I've got one suggestion inline, and a couple of general requests
- In README.md, explain that Makefile is specifically only for use with ROOT5 and is not supported otherwise. All output that needs to be trusted must use cmake
- You’ve added a lot of things to the messenger. It’d be good to document them in WCSim.mac. Here’s a non-exhaustive list
  - gamma-conversion PrimaryGeneratorAction
  - replica, half tower rotation, etc. geometry building
  - A load of optical physics things
  - (Thank you for doing it already for the tuning options in the relevant .mac file)

2023-08-10 13:44 UTC, tdealtry commented on WCSim.mac
> +#/WCSim/WCgeom nuPRISMShort_mPMT
```suggestion
#Use WCTE geometry (uncomment/delete the above)
# Use the short version of NuPRISM with 6 m tall ID
#/WCSim/WCgeom nuPRISMShort_mPMT
```
The IWCD options are already in this file above

2023-08-14 02:22 UTC, kmtsui commented
More documentations are added. Please check if you want more details in certain aspects.

2023-08-21 09:50 UTC, tdealtry approved these changes

2023-08-21 09:50 UTC, merged