Addition of working assembly based hybrid mPMT geometry.
WCSim/WCSim pull request #399
Opened 2023-12-19 22:44 UTC by patrickstowell

Merge of new realistic PMT geometry based on integration diagrams.
Issues with mPMT hits have been traced back to a rotation and offset issue in the WCPMT2 objects. This has been resolved and now weighted PMT hits are agreeing within 1-2%.

**Comparisons of the 500MeVmum_xdir validation set**
ORIGINAL PMT1 COUNTS [AVGNHIT,NPMT]: 2108.33 19826 
REALISTIC PMT1 COUNTS [AVGNHIT,NPMT]: 2059.1 19746
COMPARISON WEIGHTED HITS OLD VS NEW : 0.106341 0.104279 -> 0.98061

ORIGINAL PMT2 COUNTS [AVGNHIT,NPMT]: 599.71 188613
REALISTIC PMT2 COUNTS [AVGNHIT,NPMT]: 49.13 15504
COMPARISON WEIGHTED HITS OLD VS NEW : 0.003179 0.003168 -> 0.99654

2023-12-20 12:26 UTC, tdealtry requested changes
Thanks for this @patrickstowell Well done tracking down the discrepency!!

I've made (what turns out to be quite a lot of) comments inline, but most are trivial (typos, requests for more comments, request for removing code, etc.)

The biggest one is probably an OD free geometry (definition of this TBD. It maybe makes sense to do things differently to previous, and just have it identical except for the presence of OD PMTs). But after reading the realistic placement file I realise this will be non trivial, so won't hold this PR up for it

Another request is to use `checkOverlaps` & `checkOverlapsPMT`, which are set to true when the code is built with `-DWCSim_Geometry_Overlaps_CHECK=ON`, to turn on/off the Geant4 overlap checking. This will mean that the geometry can be debugged easily, but also it can be constructed quickly when people just need to use it. Again, I won't hold the PR up for this one

A final request is to add the new geometry option to `WCSim.mac` (commented out), along with a comment specifiying which geometry parameters effect the geo & which are ignored. It'd be nice to have that with this PR

2023-12-20 12:26 UTC, tdealtry commented on src/WCSimDetectorConfigs.cc
> +  // nID_PMTs2 = 1;
Think this is test code that can be removed?

2023-12-20 12:26 UTC, tdealtry commented on src/WCSimDetectorConfigs.cc
> +  else if(WCPMTPercentCoverage2 < 0) WCPMTPercentCoverage2 = 0.0; //protection against negative coverage
I presume you're not using this in the realisitc placement code? So can you remove these?
(I guess there could be some weird old geometry code logic reasoning for why these are required)

2023-12-20 12:26 UTC, tdealtry commented on src/WCSimDetectorConfigs.cc
> +  else if(WCPMTPercentCoverage2 < 0) WCPMTPercentCoverage2 = 0.0; //protection against negative coverage
Same with PMTs per cell, etc.

2023-12-20 12:26 UTC, tdealtry commented on src/WCSimDetectorConfigs.cc
> +  WCPMTODPercentCoverage   = 1.0; //default 1%
Again presume can be removed

2023-12-20 12:26 UTC, tdealtry commented on src/WCSimDetectorConfigs.cc
> +void WCSimDetectorConstruction::SetHyperK_HybridmPMT_WithOD_Realistic_Geometry()
It'd be very useful to have a `SetHyperK_HybridmPMT_IDOnly_Realistic_Geometry` option too

2023-12-20 12:26 UTC, tdealtry commented on src/WCSimConstructRealisticPlacement.cc
> +    G4ThreeVector EntireDetectOffset; //< Relative offset for
offset for what...?

Actually it'd be nice to comment this a little more to description to these variables (a lot are obvious, some less so)

2023-12-20 12:26 UTC, tdealtry commented on src/WCSimConstructRealisticPlacement.cc
> +    G4VisAttributes* BlackTyvekVis;
```suggestion
    // Black tyvek is place on the wall of the ID
    G4VisAttributes* BlackTyvekVis;
```
Relatedly, is the black sheet actually tyvek?

2023-12-20 12:26 UTC, tdealtry commented on src/WCSimConstructRealisticPlacement.cc
> +    G4VisAttributes* DeadSpaceVis;
```suggestion
    // Dead space is the space between ID & OD
    G4VisAttributes* DeadSpaceVis;
```

2023-12-20 12:26 UTC, tdealtry commented on src/WCSimConstructRealisticPlacement.cc
> +    G4double InnerDetectorOuterRadius;
Make it clear that ID inner is expected to be 0 (it confused me why an inner radius was required for ID, but makes sense after seeing the value below)

2023-12-20 12:26 UTC, tdealtry commented on src/WCSimConstructRealisticPlacement.cc
> +    G4double OuterDetectorOuterRadius;
Clarify what inner & outer is (think this is obvious, but ID has inner & outer too which makes less sense to me, so should be clear here)

2023-12-20 12:26 UTC, tdealtry commented on src/WCSimConstructRealisticPlacement.cc
> +    G4VisAttributes* WhiteTyvekVis;
```suggestion
    // White tyvek is placed on the instrumented (inner) side of the OD
    G4VisAttributes* WhiteTyvekVis;
```

2023-12-20 12:26 UTC, tdealtry commented on src/WCSimConstructRealisticPlacement.cc
> +    G4VisAttributes* WallTyvekVis;
```suggestion
    // Wall tyvek is placed on the inner wall of the water tank
    G4VisAttributes* WallTyvekVis;
```

2023-12-20 12:26 UTC, tdealtry commented on src/WCSimConstructRealisticPlacement.cc
> +    G4VisAttributes* RockShellVis;
Explain what the rock shell is

2023-12-20 12:26 UTC, tdealtry commented on src/WCSimConstructRealisticPlacement.cc
> +    G4VisAttributes* MainWaterTankVis;
Explain what the main water tank is

2023-12-20 12:26 UTC, tdealtry commented on src/WCSimConstructRealisticPlacement.cc
> +  // Helper Function to
unfinished comment

2023-12-20 12:26 UTC, tdealtry commented on src/WCSimDetectorConfigs.cc
> +  WCIDHeight            = 65.751*m;//54.8*m; // = 60m - 2*(60cm ID wall + 2m OD)
Please remove, as you override them in realistic placement

2023-12-20 12:26 UTC, tdealtry commented on src/WCSimConstructRealisticPlacement.cc
> +    WCBlackSheetThickness = 2*cm; // Here this was changed from 2cm, likely a typo in legacy.
The comment suggests you changed it, but you haven't...

2023-12-20 12:26 UTC, tdealtry commented on src/WCSimConstructRealisticPlacement.cc
> +    G4double NBlocksPerRing;
These sound like `int`s

Also, please explain all these!

2023-12-20 12:26 UTC, tdealtry commented on src/WCSimConstructRealisticPlacement.cc
> +    G4double CellArcLength;
Explain all these too!

2023-12-20 12:26 UTC, tdealtry commented on src/WCSimConstructRealisticPlacement.cc
> +    config.InnerDetectorVis = new G4VisAttributes(true, G4Colour(0.0,0.0,1.0,1.0));
Can you add comments to each colour line, to say what colour it is?
Actually, maybe better would be to collect all the default colours together in a readme somewhere

2023-12-20 12:26 UTC, tdealtry commented on src/WCSimConstructRealisticPlacement.cc
> +    G4double pi = 3.14159*2;
This is actually 2pi too...

2023-12-20 12:26 UTC, tdealtry commented on src/WCSimConstructRealisticPlacement.cc
> +    // Optional inner phantom for creating a new logical away from the PMT tracking one
Can you explain why this might be useful?

2023-12-20 12:26 UTC, tdealtry commented on src/WCSimConstructRealisticPlacement.cc
> +    // | #M# |
```suggestion
    // | #F# |
```

2023-12-20 12:26 UTC, tdealtry commented on src/WCSimConstructRealisticPlacement.cc
> +    // frame_block_assembly->AddPlacedAssembly(pmtmulti_offset_placement, position_high, rotation_low );
```suggestion
    // skip the top left position in the cell, as it is empty (position_high, rotation_low)
```
I like the idea you have with the empty parts having a placeholder, but prefer to have a comment instead of commented out code

Choose your favourite wording & then please repeat it for all similar lines

2023-12-20 12:26 UTC, tdealtry commented on src/WCSimConstructRealisticPlacement.cc
> +    // Then we repeatt but also add mPMT for PMT_hybrid_three_cell
```suggestion
    // Then we repeat but also add mPMT for PMT_hybrid_three_cell
```

2023-12-20 12:26 UTC, tdealtry commented on src/WCSimConstructRealisticPlacement.cc
> +// root [1] .q
Do we need this? If we do, can you add what the numbers mean? And remove uncessary lines (e.g. `.q`)

2023-12-20 12:26 UTC, tdealtry commented on src/WCSimConstructRealisticPlacement.cc
> +    // Todo: Add Diagram for OD Barrel Block
Not required for the PR, but just reminding you about your reminder

2023-12-20 12:26 UTC, tdealtry commented on src/WCSimConstructRealisticPlacement.cc
> +    // G4double phi_offset = twopi / float(NSegments);
```suggestion
```

2023-12-20 12:26 UTC, tdealtry commented on src/WCSimConstructRealisticPlacement.cc
> +      // Simple row only ID pmtt
```suggestion
      // Simple row only ID pmt
```

2023-12-20 12:26 UTC, tdealtry commented on src/WCSimConstructRealisticPlacement.cc
> +    // Hard coded row choices for
unfinished comment

2023-12-20 12:26 UTC, tdealtry commented on src/WCSimConstructRealisticPlacement.cc
> +    // Now cap the oother side
```suggestion
    // Now cap the other side
```

2023-12-20 12:26 UTC, tdealtry commented on src/WCSimConstructRealisticPlacement.cc
> +    std::cout << "" << std::endl;
Please use G4cout, G4cerr & G4endl instead
(There was some mangling when mixing these with std::cout etc in the past)

2023-12-20 16:33 UTC, tdealtry requested changes
Few more triival things to do (noticed upon compiling & running)

2023-12-20 16:33 UTC, tdealtry commented on src/WCSimConstructRealisticPlacement.cc
> +  G4ThreeVector& position,
```suggestion
  G4ThreeVector& /*position*/,
```
Unused variable

2023-12-20 16:33 UTC, tdealtry commented on src/WCSimConstructRealisticPlacement.cc
> +    G4double pi = 3.14159*2;
Can you remove these, to get rid of the compilation warnings
```
WCSimConstructRealisticPlacement.cc:310:14: warning: declaration of ‘twopi’ shadows a global declaration [-Wshadow]
     G4double twopi = 3.14159*2;
```

```suggestion
```

2023-12-20 16:33 UTC, tdealtry commented on src/WCSimConstructRealisticPlacement.cc
> +    G4double InnerTyvekRadius = config.InnerDetectorOuterRadius;
Unused variable compilation warning
```suggestion
    //G4double InnerTyvekRadius = config.InnerDetectorOuterRadius;
```

2023-12-20 16:33 UTC, tdealtry commented on src/WCSimConstructRealisticPlacement.cc
> +    int NBlocksUp = config.NBlocksUp;
```suggestion
    //int NBlocksUp = config.NBlocksUp;
```
Unused variable compilation warning

2023-12-20 16:33 UTC, tdealtry commented on src/WCSimConstructRealisticPlacement.cc
> +      std::cout << "HK FD Detector Configuration Table " << std::endl;
```suggestion
      std::cout << "HK FD Detector Configuration Table (units: mm)" << std::endl;
```

2023-12-20 16:33 UTC, tdealtry commented on src/WCSimConstructRealisticPlacement.cc
> +      std::cout << "WallTyvekOuterRadius = " << WallTyvekOuterRadius << std::endl;
```suggestion
      std::cout << "WhiteTyvekOuterRadius = " << WhiteTyvekOuterRadius << std::endl;
```
Fixing copy-paste error

2023-12-20 16:33 UTC, tdealtry commented on src/WCSimConstructRealisticPlacement.cc
> +      std::cout << "RockShellRadius = " << RockShellLength << std::endl;
```suggestion
      std::cout << "RockShellRadius = " << RockShellRadius << std::endl;
```
Fixing copy-paste error

2023-12-21 08:52 UTC, patrickstowell commented
@tdealtry Actually turning off the ODPMTs is straight forward if all we want to do is not place them but still keep the OD water volume. I can do that before the merge, but it'll need a warning as in that configuration light is still simulated in the OD water volume. To fix that we'd need to set the OD water volume to be a 'non-optical' version of the Water material so GEANT4 knows to kill photons generated in that region.

2023-12-21 09:09 UTC, patrickstowell commented on src/WCSimDetectorConfigs.cc
> +  WCPMTODPercentCoverage   = 1.0; //default 1%
All these horrible legacy variables in DetectorConfigs I am assuming they can go, but I'll need a bit of time to check they don't break anything if they are just left dangling at the values the default SK geometry puts them at. Some seem to. For now I think we should compromise by separating them out in DetectorConfigs and fixing their values with a comment to say they shouldn't do anything. Then I'll spend a bit of time repeating validations with them all removed after the merge.

2023-12-21 09:09 UTC, patrickstowell commented on src/WCSimConstructRealisticPlacement.cc
> +    G4ThreeVector EntireDetectOffset; //< Relative offset for
Removed. This was copied over because construct cylinder also mentions an offset.

2023-12-21 10:23 UTC, tdealtry commented
Yeah not simulating the light propagation in the OD region sounds like the best thing to do, otherwise we're not saving much CPU time (i.e. if we're only turning the PMTs off).

If this is complicated, can do this in a future PR (just make sure to have the warning about light propagating in the OD)

2023-12-21 10:37 UTC, tdealtry commented on src/WCSimDetectorConfigs.cc
> +  WCPMTODPercentCoverage   = 1.0; //default 1%
Sounds good

2023-12-21 14:07 UTC, tdealtry approved these changes

2023-12-21 14:07 UTC, merged

2023-12-21 14:08 UTC, tdealtry commented
Thanks @patrickstowell